# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

UdetC <- function(ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2) {
    .Call(`_doseDet_UdetC`, ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2)
}

efftox_add <- function(ep, tp, r, pie, pit, ptt, pet, ptc, pec, h_treated) {
    .Call(`_doseDet_efftox_add`, ep, tp, r, pie, pit, ptt, pet, ptc, pec, h_treated)
}

prospect_powC <- function(ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ustop, h_treated) {
    .Call(`_doseDet_prospect_powC`, ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ustop, h_treated)
}

prospect_pow_addC <- function(ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ptt, pet, ptc, pec, h_treated) {
    .Call(`_doseDet_prospect_pow_addC`, ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ptt, pet, ptc, pec, h_treated)
}

prospect_pow_add_u_C <- function(ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ustop, pstop, h_treated) {
    .Call(`_doseDet_prospect_pow_add_u_C`, ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ustop, pstop, h_treated)
}

prospect_pow_u_C <- function(ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ustop, pstop, h_treated) {
    .Call(`_doseDet_prospect_pow_u_C`, ep, er, el, eag, eal, tp, tr, tl, tag, tal, k1, k2, ustop, pstop, h_treated)
}

rcpp_hello_world <- function() {
    .Call(`_doseDet_rcpp_hello_world`)
}

